feat: Introduce shell metacharacter escaping for exec
NVIDIA/nvidia-container-toolkit pull request #491
Opened 2024-05-13 00:19 UTC by servusdei2018

In order to mitigate potential security vulnerabilities arising from shell injection attacks, this PR introduces a function to escape shell metacharacters which may be present in command-line arguments.

It's worth noting that two potential vulnerabilities still exist in https://github.com/NVIDIA/nvidia-container-toolkit/blob/973a6633b30a95e27aff4ef07772387aac961395/tools/container/nvidia-toolkit/run.go#L249-L252 and https://github.com/NVIDIA/nvidia-container-toolkit/blob/973a6633b30a95e27aff4ef07772387aac961395/tools/container/nvidia-toolkit/run.go#L275-L278 where the string `o.runtimeArgs` is directly interpolated into `cmdline`, leaving it susceptible to injection attacks. To address this, a more comprehensive solution would involve reimplementing `o.runtimeArgs` as `[]string`, allowing for proper sanitization using the introduced `oci.Escape()` function; however, this likely involves a breaking change.

2024-09-03 17:48 UTC, servusdei2018 commented
cc @elezar

2024-10-11 14:22 UTC, elezar reviewed
My one question would be whether the logic that we're implementing here exists in some third-pary package somewhere. I'm sure that `runc` for example needs to also check the arguments that are passed to its hooks.

2024-10-13 18:14 UTC, servusdei2018 commented
Hmm I believe I did look at `runc` and couldn't find the exact logic they used, I looked at Docker and they use [shellescape](https://github.com/alessio/shellescape) internally.

2025-07-10 10:19 UTC, ArangoGutierrez commented
Hey @servusdei2018, let's revise this valuable contribution. Recently, we have done a lot of hardening work, so it's worth revisiting your contribution, starting with a rebase

2025-07-11 03:36 UTC, servusdei2018 commented
Rebased @ArangoGutierrez

2025-07-14 09:52 UTC, ArangoGutierrez requested changes

2025-07-14 09:52 UTC, ArangoGutierrez commented on internal/oci/runtime_syscall_exec_test.go
> +# Copyright (c) 2021, NVIDIA CORPORATION.  All rights reserved.
```suggestion
# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
```

2025-07-14 09:52 UTC, ArangoGutierrez commented on internal/oci/runtime_syscall_exec.go
> +		return fmt.Sprintf(`"%s"`, e)
simply 
```go
return metacharRegex.ReplaceAllString(arg, `\$1`)
```

2025-07-14 09:52 UTC, ArangoGutierrez commented on internal/oci/runtime_syscall_exec.go
> +const shellMetachars = "|&;()<> \t\n$\\`"
please look into this

2025-07-14 09:52 UTC, ArangoGutierrez commented on internal/oci/runtime_syscall_exec.go
> +func Escape1(arg string) string {
theres' no need for this func to be public, also the name could be something more saying than `escape1`

2025-07-15 18:08 UTC, servusdei2018 commented on internal/oci/runtime_syscall_exec.go
> +const shellMetachars = "|&;()<> \t\n$\\`"
Looks like adding the double- and single-quote don't break anything, so I went ahead and added them to `shellMetachars`.

2025-07-16 13:24 UTC, ArangoGutierrez requested changes
Can you prepend to the commits that start with `nit`  a prefix `[no-relnote]` , thanks

2025-07-16 13:24 UTC, ArangoGutierrez commented on internal/oci/runtime_syscall_exec.go
> +func EscapeArg(arg string) string {
```suggestion
func escapeArg(arg string) string {
```

2025-07-16 13:24 UTC, ArangoGutierrez commented on internal/oci/runtime_syscall_exec.go
> +func EscapeArg(arg string) string {
I don't see why this needs to be public

2025-07-16 15:41 UTC, servusdei2018 commented on internal/oci/runtime_syscall_exec.go
> +func EscapeArg(arg string) string {
It's being referenced in https://github.com/servusdei2018/nvidia-container-toolkit/blob/b491a15571355cd6ea677dcc2abe958228cdab1e/cmd/nvidia-container-runtime/main_test.go#L102 to escape any metachars in `nvidiaRuntime` (which is currently a constant, but technically a variable as far as golint sees)

2025-07-17 08:09 UTC, ArangoGutierrez commented on cmd/nvidia-container-runtime/main_test.go
> +	cmdRun := exec.Command(oci.EscapeArg(nvidiaRuntime), oci.Escape([]string{"run", "--bundle", cfg.bundlePath(), "testcontainer"})...)
```suggestion
	cmdRun := exec.Command(oci.Escape(nvidiaRuntime)[0], oci.Escape([]string{"run", "--bundle", cfg.bundlePath(), "testcontainer"})...)
```

This way we could have `EscapeArg` private

2025-07-17 23:08 UTC, servusdei2018 commented on cmd/nvidia-container-runtime/main_test.go
> +	cmdRun := exec.Command(oci.EscapeArg(nvidiaRuntime), oci.Escape([]string{"run", "--bundle", cfg.bundlePath(), "testcontainer"})...)
That works too! Reverted

2026-05-15 21:57 UTC, rajatchopra commented
Closing this PR.
Reasoning: Shell escaping is needed when a shell interpreter is invoked. Most of the execution here happens directly (clone/fork).

Some escaping may still be required if we can verify that the executable involves the shell also.
Please re-open the PR if anyone feels otherwise.

2026-05-15 21:57 UTC, closed without merging