Spelling error corrected
NVIDIA/nvidia-container-toolkit pull request #551
Opened 2024-06-19 09:20 UTC by Weselton

Corrected spelling error: "OCI Srec" -> "OCI Spec"

2024-06-19 10:31 UTC, ArangoGutierrez approved these changes

2024-06-19 11:35 UTC, elezar requested changes
@Weselton 

Please update your commit message to:
```
[no-relnote] Fixed spelling error

Signed-off-by: German Maltsev <maltsev.german@gmail.com>
```

2024-06-19 14:42 UTC, Weselton commented
@elezar 

Updated

2024-06-19 14:48 UTC, ArangoGutierrez approved these changes

2024-06-24 10:53 UTC, elezar approved these changes

2024-06-24 13:00 UTC, merged